### ISSUE TITLE
Links in brackets-cont/brackets/wiki are pointing to adobe/brackets/wiki

### ISSUE THREAD

**Issue by sprintr** [brackets-cont/brackets#10]
Links in brackets-cont/brackets/wiki are pointing to adobe/brackets/wiki. This should be fixed.

One more thing that I want to point out is that [our wiki](https://github.com/brackets-cont/brackets/wiki/Troubleshooting) should not contain a discontinuation notice anywhere.

**Comment by ScanuNicco** [comment]
I don't know if this can be done via a PR, but fixing the wiki should be pretty simple. All the links can be fixed using the Replace In Files function in Brackets.

**Comment by sprintr** [comment]
Yeah it can't be edited via a PR so someone with with push access can do it. We also shouldn't allow everyone to edit the wiki as we faced several spamming issues with the wiki in the past.

**Comment by ScanuNicco** [comment]
The wiki links have been fixed.
