### ISSUE TITLE
Chore: Merge remote file adapter to core: change from Phoenix

### ISSUE THREAD

**Issue by abose** [brackets-cont/brackets#108]
Merge in the following changes from phoenix for remote file improvements: 
* https://github.com/aicore/phoenix/pull/274
* https://github.com/aicore/phoenix/pull/275

## This brings in
* Move remote file adapter to core from extension as reading HTTP/HTTPS remote content as a file is a core requirement that any extension should be able to use. 
* Added support for file reads on any browser supported encoding from HTTP/HTTPS links instead of just defaulting to utf-8 reads
* Adds support for github and gitlab file URL opening with https://github.com/aicore/phoenix/pull/275

**Comment by Rishi6229** [comment]
Can I contribute in this issue?

**Comment by charlypa** [comment]
@Rishi6229 Thanks for your interest. You may contribute to this issue

**Comment by Rishi6229** [comment]
since I have zero experience in open source contribution will you please guide me from where should I start ?

**Comment by charlypa** [comment]
@Rishi6229 
You may follow [Getting Started](https://github.com/brackets-cont/brackets/blob/master/CONTRIBUTING.md) to to start contribution to brackets.

**Comment by TatoAndTatoOnly** [comment]
Tried to fix (#129).

**Comment by abose** [comment]
merged in from https://github.com/brackets-cont/brackets/pull/188
