### ISSUE TITLE
Is possible compile in ubuntu?

### ISSUE THREAD

**Issue by dacorsa** [brackets-cont/brackets#110]
npm run build

> Brackets@2.0.1-0 build
> grunt build

Running "write-config:dist" (write-config) task

Running "eslint:src" (eslint) task

Running "jasmine:src" (jasmine) task
Testing jasmine specs via phantom
>> Error: Script error
>> http://requirejs.org/docs/errors.html#scripterror at
>> .grunt/grunt-contrib-jasmine/require.js:31 
>> .grunt/grunt-contrib-jasmine/require.js:14 z
>> .grunt/grunt-contrib-jasmine/require.js:31 
>> Error: Script error
>> http://requirejs.org/docs/errors.html#scripterror at
>> .grunt/grunt-contrib-jasmine/require.js:31 
>> .grunt/grunt-contrib-jasmine/require.js:14 z
>> .grunt/grunt-contrib-jasmine/require.js:31 
>> Error: Script error
>> http://requirejs.org/docs/errors.html#scripterror at
>> .grunt/grunt-contrib-jasmine/require.js:31 
>> .grunt/grunt-contrib-jasmine/require.js:14 z
>> .grunt/grunt-contrib-jasmine/require.js:31 
>> Error: Load timeout for modules: text!language/languages.json_unnormalized2,i18n!nls/strings_unnormalized3,i18n!nls/urls_unnormalized4,i18n!nls/strings-app_unnormalized5,text!config.json_unnormalized6
>> http://requirejs.org/docs/errors.html#timeout at
>> .grunt/grunt-contrib-jasmine/require.js:31 
>> .grunt/grunt-contrib-jasmine/require.js:14 z
>> .grunt/grunt-contrib-jasmine/require.js:16 w
>> .grunt/grunt-contrib-jasmine/require.js:16 

Warning: PhantomJS timed out, possibly due to an unfinished async spec. Use --force to continue.

Aborted due to warnings.
npm ERR! code 90
npm ERR! path /app/brackets
npm ERR! command failed
npm ERR! command sh -c grunt build

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-12-29T11_13_58_765Z-debug.log

 grunt build
Running "write-config:dist" (write-config) task

Running "eslint:src" (eslint) task

Running "jasmine:src" (jasmine) task
Testing jasmine specs via phantom
>> Error: Script error
>> http://requirejs.org/docs/errors.html#scripterror at
>> .grunt/grunt-contrib-jasmine/require.js:31 
>> .grunt/grunt-contrib-jasmine/require.js:14 z
>> .grunt/grunt-contrib-jasmine/require.js:31 
>> Error: Script error
>> http://requirejs.org/docs/errors.html#scripterror at
>> .grunt/grunt-contrib-jasmine/require.js:31 
>> .grunt/grunt-contrib-jasmine/require.js:14 z
>> .grunt/grunt-contrib-jasmine/require.js:31 
>> Error: Script error
>> http://requirejs.org/docs/errors.html#scripterror at
>> .grunt/grunt-contrib-jasmine/require.js:31 
>> .grunt/grunt-contrib-jasmine/require.js:14 z
>> .grunt/grunt-contrib-jasmine/require.js:31 
>> Error: Load timeout for modules: text!language/languages.json_unnormalized2,i18n!nls/strings_unnormalized3,i18n!nls/urls_unnormalized4,i18n!nls/strings-app_unnormalized5,text!config.json_unnormalized6
>> http://requirejs.org/docs/errors.html#timeout at
>> .grunt/grunt-contrib-jasmine/require.js:31 
>> .grunt/grunt-contrib-jasmine/require.js:14 z
>> .grunt/grunt-contrib-jasmine/require.js:16 w
>> .grunt/grunt-contrib-jasmine/require.js:16 

Warning: PhantomJS timed out, possibly due to an unfinished async spec. Use --force to continue.

 grunt build --force
Running "write-config:dist" (write-config) task

Running "eslint:src" (eslint) task

Running "jasmine:src" (jasmine) task
Testing jasmine specs via phantom
>> Error: Script error
>> http://requirejs.org/docs/errors.html#scripterror at
>> .grunt/grunt-contrib-jasmine/require.js:31 
>> .grunt/grunt-contrib-jasmine/require.js:14 z
>> .grunt/grunt-contrib-jasmine/require.js:31 
>> Error: Script error
>> http://requirejs.org/docs/errors.html#scripterror at
>> .grunt/grunt-contrib-jasmine/require.js:31 
>> .grunt/grunt-contrib-jasmine/require.js:14 z
>> .grunt/grunt-contrib-jasmine/require.js:31 
>> Error: Script error
>> http://requirejs.org/docs/errors.html#scripterror at
>> .grunt/grunt-contrib-jasmine/require.js:31 
>> .grunt/grunt-contrib-jasmine/require.js:14 z
>> .grunt/grunt-contrib-jasmine/require.js:31 
>> Error: Load timeout for modules: text!language/languages.json_unnormalized2,i18n!nls/strings_unnormalized3,i18n!nls/urls_unnormalized4,i18n!nls/strings-app_unnormalized5,text!config.json_unnormalized6
>> http://requirejs.org/docs/errors.html#timeout at
>> .grunt/grunt-contrib-jasmine/require.js:31 
>> .grunt/grunt-contrib-jasmine/require.js:14 z
>> .grunt/grunt-contrib-jasmine/require.js:16 w
>> .grunt/grunt-contrib-jasmine/require.js:16 

Warning: PhantomJS timed out, possibly due to an unfinished async spec. Used --force, continuing.

**Comment by abose** [comment]
Thanks for raising the issue. We are with the Linux community on this and are working on top priority for a Linux port. 
Adobe had ditched support for Linux in its final build of brackets and I'm afraid it is due to a CEF platform limitation with the older CEF builds that Adobe used for brackets.
The Brackets community is now working on a larger platform migration to move away from CEF-based brackets-shell for Linux support. We expect to complete it by March 2022 and will have Linux builds for most Linux flavors soon after.
More details can be found here: https://github.com/brackets-cont/brackets/issues/26

**Comment by abose** [comment]
Closing as we do not plan to support brackets shell builds in the future after electron port

follow #26 for electron migration status

**Comment by abose** [comment]
- https://github.com/brackets-cont/brackets/issues/112
