### ISSUE TITLE
Brackets.io registry “Sign in with GitHub” link redirects to “localhost:3000”

### ISSUE THREAD

**Issue by TatoAndTatoOnly** [brackets-cont/brackets#127]
### Description

The “Sign in with GitHub” link on [registry.brackets.io](url) tries to redirect to “localhost:3000”. This issue was mentioned in #15 in [a comment](https://github.com/brackets-cont/brackets/issues/15#issuecomment-914227548), but the issue was closed.

### Steps to Reproduce

1. Open registry.brackets.io
2. Click “Sign in with GitHub”
3. Enter your account details and click “Authorize”

**Expected behavior:** You should be signed in to GitHub on the extension registry.

**Actual behavior:** You get redirected to a nonexistent “localhost:3000”

### Versions

I have tested this on:

- MacOS Monterey 12.1 running Chrome
- iOS 15.2.1 tablet running Safari

**Comment by abose** [comment]
We are building a new extensions registry that will be launched by the Feb - March time frame. 
So we are not likely to fix this issue in the old registry.
