### ISSUE TITLE
Trying to revive the community

### ISSUE THREAD

**Issue by Huygenz** [brackets-cont/brackets#13]
I'm trying to get the flatlined community up again.

I just set up a Brackets community server on Discord. I'm also trying to revive the existing subreddit again after it has been abbandoned and closed down for nearly two years. **I'll link these places to the new website and this repository.**

The community is almost dead atm. There's not much engagement right now and people are unsettled regarding September 1st. I'm trying my best to get it alive again, so every contribution and input is highly appreciated: The new Discord is empty and the subreddit is lacking active users. 

https://discord.gg/rBpTBPttca
https://www.reddit.com/r/brackets/

PS: If this isn't the right place to consider such things, feel free to delete this post.

**Comment by ScanuNicco** [comment]
I can submit a PR to add the discord link to the new website.

**Comment by Huygenz** [comment]
Great idea, I'm ok with it.

**Comment by kanta-mir** [comment]
use this link . copy the link and past in the url box of the themes and plugins
https://cdn.amuslim.org/brackets/

**Comment by Huygenz** [comment]
That doesn't contribute to the topic.
Anyways, since all is set up and in good shape, I'll close this now.
Thank y'all!
