### ISSUE TITLE
Migrate Issues from the Adobe Repo.

### ISSUE THREAD

**Issue by ScanuNicco** [brackets-cont/brackets#14]
Someone with write access needs to use https://github.com/ahadik/git_mover to copy all of the issues from adobe/brackets to this repo. This needs to be done before September 1st or all of the existing issues will be lost when adobe deletes their repo. It would also be helpful if the binaries for Brackets 1.14.2 were copied to this repo so that people can continue to download them after September 1st.

**Comment by abose** [comment]
Hey guys.  we have archived all issues into https://github.com/brackets-archive/  just in case. 

Our bots are archiving issues in brackets repo to a private repo(to be made public after the copy is done) to prevent unwanted `@mention` notifications. It has been running for a day as GitHub limits tps to 2000 per hour. We should be done by tomorrow for all brackets issues.

Point to note before cloning all issues that we found out: Prevent notifications for `@mentions`  when an issue is copied to prevent spamming brackets github users. (Workaround: use a private repo to copy to and then make it public.)

**Comment by yogo1212** [comment]
@abose cool stuff!

**Comment by dym-sh** [comment]
> On September 1, 2021, Adobe will end support for Brackets.

> **end support**

not "delete repo"

**Comment by ScanuNicco** [comment]
I was under the impression that adobe would delete the repo, however it seems like that is not going to happen, so this isn't really an issue anymore.
