### ISSUE TITLE
couldn't download brackets from brackets.io

### ISSUE THREAD

**Issue by chitanyachitturi** [brackets-cont/brackets#17]
MacOS BigSur Version 11.5.2

**Comment by N-yaya** [comment]
the doawload button for brackets not reacting

**Comment by ScanuNicco** [comment]
This is caused by a cert error on the new S3 bucket that the website is using. For now, you can download Brackets from the old Adobe repo: https://github.com/adobe/brackets/releases

**Comment by King-of-the-Bill** [comment]
Why does this main fork not have .msi or .dmg installers in the releases? This would be the best fix while the site gets its act together.

**Comment by abose** [comment]
Duplicate of https://github.com/brackets-cont/brackets/issues/19
Closing.
