### ISSUE TITLE
Tweaking and reusing Themes

### ISSUE THREAD

**Issue by kanta-mir** [brackets-cont/brackets#18]
I want to reuse the already present themes or make a custom theme for brackets. For example I only want to add matching brackets glow. 

I there a boilerplate setup from where I can start. 

Thanks

**Comment by Huygenz** [comment]
That's not really an "issue" ;)
Feel free to join us at discord or reddit, that may be a better place to get info regarding your topic.

- https://www.reddit.com/r/brackets/
- https://discord.com/invite/MbVTsdwu3u

**Comment by abose** [comment]
Please use Brackets Discord for any support.
As this is not a dev issue, closing.
