### ISSUE TITLE
Sanity test pass in windows v2.1.0

### ISSUE THREAD

**Issue by abose** [brackets-cont/brackets#193]
Run against last pass: https://github.com/brackets-cont/brackets/issues/86

Run test on:

https://github.com/brackets-cont/brackets/commit/91ef47e5f0e71a10f47c33bd0e3ff548ee62a5f7
Previous test:
https://github.com/brackets-cont/brackets/commit/4340a77515eeffd38b26cb959992e8390159268e

**Comment by mathewdennis1** [comment]
Test ran for [(91ef47e) ](https://github.com/brackets-cont/brackets/commit/91ef47e5f0e71a10f47c33bd0e3ff548ee62a5f7) -->> https://docs.google.com/spreadsheets/d/1ngUlQ-OgQYyIMmVTfARHjN0-RVMiDQ-KiHNzg6hbDEM/edit#gid=0
