### ISSUE TITLE
Can't install npm packages of brackets

### ISSUE THREAD

**Issue by LehanMusthafa** [brackets-cont/brackets#20]
I was trying to clone this project and start in a dev environment by following this guide: https://github.com/adobe/brackets/wiki/How-to-Hack-on-Brackets

But trying to do the fifth step, which is running `npm install` I get an error. Here is the preview of the error:
<img width="734" alt="cmd" src="https://user-images.githubusercontent.com/73033947/134133156-6e84333d-a2a8-4ed2-946f-8cbf1515e122.PNG">

Can anyone help regarding this issue...

**Comment by ScanuNicco** [comment]
The dependencies are very out of date Try using the source from #2 and see if that helps.
