### ISSUE TITLE
How long should we wait to see a Linux version?

### ISSUE THREAD

**Issue by realKarthikNair** [brackets-cont/brackets#204]
First of all, thank you to the developer community behind brackets-cont to revive Brackets.

<b>But how long before we get a Linux version?</b?

**Comment by abose** [comment]
Hi @realKarthikNair We are currently working on a browser version of brackers- https://phcode.dev and once the project attains stability (hopefully in  two to three months), we will begin porting brackets to Linux.

**Comment by realKarthikNair** [comment]
@abose yes I'm aware of Phoenix. So you guys are planning to make a wrapper out of it as the linux version i assume?

**Comment by abose** [comment]
More or less, we should be able to port it to electron and then it should run in almost any platform supported by electron/browser.

**Comment by realKarthikNair** [comment]
Okay gotcha. Thanks for responding.
