### ISSUE TITLE
Brackets app is crashing every time I open it (on a Mac running Mojave)

### ISSUE THREAD

**Issue by robert-phillips-hpe** [brackets-cont/brackets#21]
### Prerequisites

* [x] Can you reproduce the problem with `Debug -> Reload Without Extensions`? no, since I can't open it long enough to make changes to the config.
* [x] Did you perform a cursory search to see if your bug or enhancement is already reported?
Yes, I searched for "crash" "segmentation fault" and "KERN_INVALID_ADDRESS"
* [x] Did you read the [Troubleshooting guide](https://github.com/brackets-cont/brackets/wiki/Troubleshooting)?
Yes, I couldn't find anything that is similar to what I'm seeing

For more information on how to write a good bug report read [here](https://github.com/brackets-cont/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/brackets-cont/brackets/blob/master/CONTRIBUTING.md)

### Description

Every time I open the app, it crashes immediately and generates a crash report

### Steps to Reproduce

1. Open the app

**Expected behavior:** [What you expected to happen]
That the app would open

**Actual behavior:** [What actually happened]
it crashes
### Versions
Version:               1.14.2 (1.14.2)

Please include the OS and what version of the OS you're running.
Please include the version of Brackets. You can find it under `Help -> About Brackets` (Windows and Linux) or `Brackets -> About Brackets` (macOS)

I can't get the brackets information requested above, since I can't open the app.  However, the crash file indicates I'm at version 1.14.2.  My mac is at 10.14.6.  Brackets has been stable until yesterday.  Prior to it crashing, my company installed "zscaler".  It didn't immediately crash after that so I don't know if that's the cause.  some time (I didn't measure it) later, I went to start the app and it wouldn't start anymore, just immediately crashes.  
[Brackets_2021-09-30-130303_C02SX4B9GTDY.crash.txt](https://github.com/brackets-cont/brackets/files/7261334/Brackets_2021-09-30-130303_C02SX4B9GTDY.crash.txt)

**Comment by ScanuNicco** [comment]
Maybe try with 1.14.1 and see if that crashes too.

**Comment by robert-phillips-hpe** [comment]
That seems to be working, thanks!  Do you think what I've provided is enough to find and fix a bug?

**Comment by abose** [comment]
@robert-phillips-hpe Please try brackets 2.0 from bracets.io

**Comment by robert-phillips-hpe** [comment]
I found 2.0.1 on brackets.io and installed it.  So far, so good.  The app was immediately crashing before and it's not now so I assume this issue is resolved.

**Comment by abose** [comment]
Closing as fixed.
