### ISSUE TITLE
files.brackets.io seems down permanently, does anyone have the backup?

### ISSUE THREAD

**Issue by willnode** [brackets-cont/brackets#22]
So `brackets-shell` uses files in S3 storage of files.brackets.io, but the bucket is gone.

https://github.com/brackets-cont/brackets-shell/blob/c180d7ea812759ba50d25ab0685434c345343008/Gruntfile.js#L328

So we can't build the shell unless if it back available. Theoretically we can bundle the depedencies ourselves but CEF alone is a gigantic project.

**Comment by ScanuNicco** [comment]
Someone already managed to get Brackets running on Electron so maybe we should just switch to that. https://github.com/quadre-code/quadre

**Comment by charlypa** [comment]
https://github.com/brackets-cont/brackets/projects/3

**Comment by abose** [comment]
We will be moving to electron in the long term(2022). 
Closing as won't fix.
