### ISSUE TITLE
Wot! after all this time nothing for Linux?

### ISSUE THREAD

**Issue by Romane-T** [brackets-cont/brackets#230]
Have tried running the Windoze version under emulation, but useless - won't run, freezes and crashes.
No point trying the version for Apple machines - don't have an Apple machine.
This used to be an excellent editor, but now... Dunno, can't run it.
And no, I'm not compiling it myself - don't have the knowledge, the skills, nor the inclination.
So now, so far as Linux users are concerned, Brackets has simply become another waste of space in the library of good software.

**Comment by lewri** [comment]
See #112  . They're doing their best but it's now an open source community.

Inside that meta issue some suggestions have also been posted, such as Wine, or using the Flatpak version of Adobe's last release (outdated).

**Comment by Romane-T** [comment]
Good morning Lewri

First, many thanks for your courteous reply, despite the tone of my 
initial post.

I have tried using Wine to run it - absolute failure, won't run. Useless 
waste of hard-drive space.

I am currently running the Flatpak version, which is, as you said, out 
of date. So far out of date that, despite considerable reluctance, am 
very seriously considering a shift to Microsoft's Editor (VSCode) of 
which Flatpak has a copy which is free of all the telemetry and so on. 
Even with the telemetry and etc, after Brackets, VSCode is the next best 
thing

If I may speak bluntly and be excused ahead of speaking. This is not the 
only developer community using the extremely weak and abysmally poor 
excuse of being "open-source". Sorry, that does not wear. Open source or 
closed source makes no difference.

As no version for Linux is forthcoming only hastens my _permanent_ move 
away from Brackets. While Adobe had it, it was, for me, very good, and 
when the first inklings of a fork was mooted, I held high hopes. Now, 
not a single one of those hopes lives.

**Comment by rubanunes** [comment]
Have you tried VSCodium?

**Comment by Romane-T** [comment]
Thank you. Yes. Same issues for me as the product itself from Microsoft 
- it does not serve my needs accept barely.

The telemetry and etc. from Microsoft in the product as they distribute 
it, is not something that am concerned about at all. I even managed to 
track down a Debian repository, supported by Microsoft, which makes 
keeping it up to date simple for me (I run Debian Testing).

I am a simple man - it either serves my need or it doesn't. It doesn't 
serve my needs, not in any any of its several presentations.

And trying to run the current Brackets under Wine - total waste of time; 
complete failure.

**Comment by fturiot** [comment]
old node version used and lot of security problem

**Comment by abose** [comment]
Duplicate of https://github.com/brackets-cont/brackets/issues/112
closing.
