### ISSUE TITLE
How to update an extension on Brackets Extension Registry?

### ISSUE THREAD

**Issue by MerryPanda** [brackets-cont/brackets#239]
It doesn't allow to log in with GitHub, it redirects to localhost.

Or how to add an extension then?

**Comment by abose** [comment]
Please attach the extension as a zip file in this issue to publish. 

We are building a new extensions registry that will be launched by the Feb - March 2023 time frame. So extension updates are by issues only at this time.

**Comment by MerryPanda** [comment]
Ok, thanks :)

[brackets-productivity-project-files-search.zip](https://github.com/brackets-cont/brackets/files/10147061/brackets-productivity-project-files-search.zip)

**Comment by abose** [comment]
@MerryPanda Updated and verified. 
Please reopen the issue if there is anything more or for any updates.
