### ISSUE TITLE
Investigate switch to electron.JS from brackets shell.

### ISSUE THREAD

**Issue by abose** [brackets-cont/brackets#26]
Maintaining brackets shell is costly and redundant with electronJS. Investigate if we can transition into electron js.

**Comment by abose** [comment]
It looks like quadre maintainers would not be able to support us with the port. We investigated quadre and have the following notes:
1. Quadre is based on a version of brackets-electron that looks to be in sync with brackets 2017 version. 
2. The effort required would be heavy to merge in brackets and quadre at this stage. Quadre has moved to typescript and a simple merge would almost certainly fail. A large-scale feature migration effort would also be required, and I'm not entirely sure that we have sufficient resources/time/reason to re-engineer vscode language server code in brackets that came with the last releases.
3. We will most likely not get support from quadre Engg for the migration, which would be problematic as the codebase is largely maintained by ficristo and we cannot fall back to any other community members for help. 
4. There are a lot of breaking changes in quadre: extension management, node layer, lack of unit tests that is not yet ready for production launch and require more work.

With these I guess its safe to conclude:
1. A direct merge of Quadre to brackets would be cost-prohibitive to implement.
2. We can merge in parts of quadre like electron build/installer generation scripts and the shell compatibility layer for electron from quadre with existing brackets code. This is much simpler and wont be a huge breaking change.
3. We cannot do this in a November release with our resources.
4. We can work on an electron port parallel in a separate branch with help from @sprintr who is actively working on a port with existing brackets core and merge in parts from quadre as required during the port.

**Comment by abose** [comment]
@rileyhawk1417 Maintaining brackets shell is hard as we need to keep up with chromium(CEF) updates and that used to break our integrations regularly across different platforms. For Eg., we can't create Linux builds now as CEF inside brackets shell is ancient and the latest Linux distros do not ship with the required dependencies that CEF inside brackets shell needs. 

Updating CEF regularly is not trivial. Updates usually had brought in focus issues and other platform-specific issues that we have to address separately in the shell. 

Similarly, brackets ship with an ancient node binary which we have not dared to update since node 6.0. Electron comes with built-in node support that is kept up to date but the electron team.

Electron is a well-maintained port that does all these things for us for free. It is a safe long-term bet and the brackets devs can concentrate more on developing rich features for brackets than worry about the shell component.

**Comment by Uka-Uka** [comment]
Hey @sprintr, do stuff!!

**Comment by abose** [comment]
Will resolve: https://github.com/brackets-archive/bracketsIssues/issues/14256

**Comment by abose** [comment]
We have formally reached the conclusion to switch to electron for brackets shell.

Further progress will be tracked in this project: https://github.com/brackets-cont/brackets/projects/3

**Comment by OdinVex** [comment]
>     shell did not support custom window decorators

That's the last thing this universe needs, why is everyone trying to savagely violate user accessibility with CSD? FFS...

**Comment by KaKi87** [comment]
Hello,
May I suggest using Tauri instead of Electron ? :sweat_smile: 
Thanks

**Comment by abose** [comment]
@KaKi87 We are using Tauri instead of Electron. The work has started.
![image](https://user-images.githubusercontent.com/5336369/208735690-848eef80-8646-497d-916a-7b5ba876fda0.png)

**Comment by abose** [comment]
Closing as we have chosen to use Tauri instead of Electron.
Please track progress at https://github.com/orgs/phcode-dev/projects/1

**Comment by KaKi87** [comment]
Thanks but that link doesn't work :thinking:

**Comment by abose** [comment]
> Thanks but that link doesn't work thinking

It was set to private. Should be visible now as made public.
