### ISSUE TITLE
Fix for broken Live Preview after latest chrome update

### ISSUE THREAD

**Issue by abose** [brackets-cont/brackets#262]
Live preview in brackets fails after the latest Chrome update (Version 111). You will get the following error:
![image](https://user-images.githubusercontent.com/5336369/223937093-70a15eed-1f2b-4a76-8044-dedeb72a6967.png)

# The fix:
 > A new release of Brackets with the fix will be available by 15'th march.  Please follow this issue to track.

Till we release the update, you can fix the issue by one of the two methods:

## Method 1: Use [phcode.dev](https://phcode.dev) - the browser version of Brackets.
[Phoenix brings all the powers of Brackets and its Extensions to web browsers; no install needed.
 Click here to open phcode.dev](https://phcode.dev/) . New native builds of phcode and Brackets are [in the works](https://github.com/orgs/phcode-dev/projects/1) and will be available by June-July.
![image](https://user-images.githubusercontent.com/5336369/223938143-01ea2082-ee7b-4016-b28a-c8ed56340563.png)

## Method 2: Enable Experimental live preview in Brackets
1. open `file menu > Enable Experimental Live Preview`
2. Live preview should now work in brackets.
 > Note that experimental live preview does not work with custom preview servers in project settings
![image](https://user-images.githubusercontent.com/5336369/223938257-92f9d795-8d6a-404a-8d37-453aba330401.png)

**Comment by abose** [comment]
Looks like webstorm is affected too: [link](https://youtrack.jetbrains.com/issue/WEB-59211/Cant-attach-debugger-to-Chrome-Dev-111-Invalid-handshake-response-getStatus-403-Forbidden) . But they have a fix, checking the fix.

**Comment by abose** [comment]
Issue fixed in mac and windows.  Pending testing and detailed test suite run as this is a high-impact code change.

**Comment by abose** [comment]
Release published fixing the issue: https://github.com/brackets-cont/brackets/releases/tag/v2.2.0
Waiting for more thorough testing before publishing to site and sending update notification.

**Comment by abose** [comment]
New release is updated at https://brackets.io . 
Release notification to be updated tomorrow.

**Comment by abose** [comment]
A new release is posted. Closing.

**Comment by anna007108** [comment]
This issue exists again with macOS and the new version of Chrome. Can someone fix it please?

**Comment by clintaire** [comment]
Imagine reading this article and finding no solutions; this is absurd. When utilizing native windows or linux software designed to work on a Mac, I usually run into some issue, and instead of using the software more quickly and productively, I end up wasting half of my time hunting for solutions that never provide reasonable solution or dead end support these apps for Mac.

**Comment by rpralica** [comment]
Maybe this is not the right place to ask but can someone tell me how to install Brackets 2 on Linux Mint

**Comment by davlhd** [comment]
This is still an issue on macOS

**Comment by abose** [comment]
> This is still an issue on macOS

Please download the latest native builds from https://phcode.io . We have a new mative build available there.
