### ISSUE TITLE
Live Preview does not work anymore with Chrome on macOS

### ISSUE THREAD

**Issue by anna007108** [brackets-cont/brackets#292]
Chrome Version:
**115.0.5790.114**

Operating System:
**macOS 13.4.1 (M2 MacBook Pro)**

Brackets Version:
**2.2 Build 2.2.0-17942**

Issue:
**The live preview doesn't work anymore. It worked with an earlier version of Chrome, but with the new one not anymore. Using the experimental version works, but I prefer the classic one. How can this be fixed?**

**Comment by abose** [comment]
@anna007108 What error message do you get with live previews?

**Comment by anna007108** [comment]
@abose Do you have any idea how to fix it?

**Comment by anna007108** [comment]
@abose Do you have an idea how to fix it?

**Comment by abose** [comment]
Please update brackets from brackets.io . This issue was fixed a while back. 

If it still doesn't work, select `file menu - enable experimental live preview` should fix it.

**Comment by anna007108** [comment]
@abose Thanks for your answer. I remember that it didn't work anymore a few months ago, then I updated Brackets, and it worked again. But since the new Chrome version, it doesn't work again. I installed Brackets many times, also Chrome, and it just doesn't work anymore. Actually I got it to work with installing an earlier version of Chrome (I think it was from June), but it automatically updated.

**Comment by anna007108** [comment]
The new macOS and/or Chrome update fixed the issue.

**Comment by anna007108** [comment]
The new macOS and/or Chrome update fixed the issue.
