### ISSUE TITLE
Linux Version

### ISSUE THREAD

**Issue by codeAyushOSS** [brackets-cont/brackets#304]
Can there be a linux version? I'm new into web development. Don't have a nice laptop. I use linux. Please bring a linux version.

thanks in advance

 #Sorry for bad English

**Comment by ScanuNicco** [comment]
This is a duplicate of #112 . Linux support is being worked on.

**Comment by inson1** [comment]
@codeAyushOSS this should be closed now right?

**Comment by codeAyushOSS** [comment]
Yup.....sry I don't actually keep a track of these sry
