### ISSUE TITLE
Renaming the Extension name, Github Repo and files

### ISSUE THREAD

**Issue by a-bentofreire** [brackets-cont/brackets#330]
Hi,
I'm the owner of the extension BracketsToIX which is on the repo: https://github.com/a-bentofreire/bracketstoix

I would like to:
1. change my repo name to: editortoix
2. move all the files and folders to a subfolder called phoenix
3. have the name visible to the user as EditorToIX instead of BracketsToIX, the internal ids  can be the same as long as to the user is called EditorToIX

Is there a problem with these changes regarding the .github/workflows ?

**Comment by abose** [comment]
@a-bentofreire do you have to do this in brackets or Phoenix code?

**Comment by a-bentofreire** [comment]
I'm sorry, but your question isn't clear.
I'm talking about renaming my repo name, files and folders on my github repo, including the display name but keeping the name on the package.json, but it must work with Phoenix code workflows in order for the user on Phoenix code see the same extension but with a different display name.

the github repo is  https://github.com/a-bentofreire/bracketstoix and it will be change to https://github.com/a-bentofreire/editortoix. 
According to https://github.com/phcode-dev/phoenix/wiki/How-To-Write-Extensions-And-Themes , as long as I create a zip it should be ok.
the package name will continue to be: github-a-bentofreire-bracketstoix but the repo name will be editortoix, and the zip file will be editortoix.zip. Is this correct?

**Comment by a-bentofreire** [comment]
I found the solution.

**Comment by abose** [comment]
@a-bentofreire The only thing to notevis that the extension id is tied to the github user:repo handle. Everything else can be changed by just updating the fields in package.json . did it work as expected?

**Comment by a-bentofreire** [comment]
Hi.
Yes, it worked. It didn't in the first time because I dragged the file to the description, not to the attached files.
So, it looks like it will update, it's still not available with the new name on extensions manager, but I just did it a few minutes ago
I remember, you mention that you remove the duplicate. That is important, since I see there is already 93 downloads of the duplicate extension, that is the old BracketsToIX but none of the new version.

**Comment by a-bentofreire** [comment]
It did publish correctly after all the changes that I did.
Internal the id it's the same : "github-a-bentofreire-bracketstoix" but visually it's EditorToIX.
The other one called BracketsToIX should be deleted, someone fork it.
![EditorToIX](https://github.com/user-attachments/assets/afd17eea-9d1a-4ea2-83f7-a968187118cb)

**Comment by abose** [comment]
@a-bentofreire so the pending thing is to delete brackets to ix from our end right?

**Comment by a-bentofreire** [comment]
Correct, delete the bracketstoix your end, which was a fork done by someone else,
please, just bear in mind that EditorToIX internal name is github-a-bentofreire-bracketstoix and this **shoudn't be** deleted

**Comment by abose** [comment]
@a-bentofreire Extension with id `bracketstoix` removed. Got busy last week with the new release, sorry for the delay.

**Comment by a-bentofreire** [comment]
@abose Thank you so much. I tried to open a phcode on a private window, and search for toix, and now it only shows my extension. This issue is solved.
