### ISSUE TITLE
New Website

### ISSUE THREAD

**Issue by ScanuNicco** [brackets-cont/brackets#4]
Many of the links on readme.md still point to the old brackets website (brackets.io). This is not great as adobe will likely take down that website after September. Maybe we should create a new website using GitHub Pages so that this fork has its own website.

**Comment by luke2m** [comment]
I agree that this fork should have a website. I have an open issue in the brackets.io repo that asks for licensing. If that does not get a reply, I am willing to make a new website. However, the API docs, etc. would be nice to copy over. Also, there are many links to the original Brackets wiki as well. Although it will probably not get taken down, it would be good to copy them over to this repository. Would someone with push access clone that wiki and push it to this project? I can do that as well if given access. I'm not a big javascript or desktop coder, but would like to help this project out as much as I can.

**Comment by ScanuNicco** [comment]
I noticed that there is a older version of the Brackets website under the gh-pages branch of this repo. That is presumably licensed under the MIT license, so if you don't get a reply we could just build off that.

**Comment by thornygravy** [comment]
I'm a noob but I'm here in support. I have a little website background, so not sure what I could do but I'd be glad to help.

**Comment by Huygenz** [comment]
Same here let's get this going! 

I'm owner of /r/brackets on reddit, please let me know if I can contribute somehow (just a webdesigner, not a great coder..).

**Comment by luke2m** [comment]
I just received confirmation [1] from someone at Adobe that it’s fine to use the original website. I’ll be working on it soon when I have some time. @yogo1212 did you start this? Would you make a brackets-cont.github.io repo I can add to or add me to the org so I can do that? Thanks.

[1].  https://github.com/adobe/brackets.io/issues/247#issuecomment-879193121

**Comment by Huygenz** [comment]
Great news! That's a good base to work with.

Let me know how I could contribute. I got some spare time on my hands (homestudies until October) and could do html/css or setting up a CMS. Alas, I don't have webspace. I could contribute texts (german speaker) or spread the word on reddit (/r/brackets seems dead at the moment, it was closed for about a year because of a vanishing mod). I'm trying to revive it rn.

If anybody has an idea, let me know.

**Comment by yogo1212** [comment]
@luke2m yes, i did start this - despite my very limited ability to contribute.

right now, brackets need people like you who continue to add to it.
once it's gained some traction, there will still be time for some organizing.

i just couldn't stand by seeing the project die a foreseeable death :-)

**Comment by ScanuNicco** [comment]
@luke2m I received an email from Adam Lehman (The same person who you talked with in https://github.com/adobe/brackets.io/issues/247) and he said that he owns the brackets.io domain and intends to keep the site and extension registry alive beyond September. I'm guessing that website development will transfer from adobe/brackets.io to brackets-cont/brackets-cont.github.io, as the old repo is still owned by adobe. The new website is currently at https://brackets-cont.github.io/, so I think it's time to close this issue.

**Comment by luke2m** [comment]
@ScanuNicco that's great news. I just reverted the site to before the depreciation announcement, and changed or commented out some of the links. PRs welcome :-)
