### ISSUE TITLE
Check for Updates not working

### ISSUE THREAD

**Issue by charlypa** [brackets-cont/brackets#44]
### Prerequisites

* [x ] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [x ] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [ x] Did you read the [Troubleshooting guide](https://github.com/brackets-cont/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/brackets-cont/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/brackets-cont/brackets/blob/master/CONTRIBUTING.md)

### Description

Brackets errors to check for an update

### Steps to Reproduce

Click Help->CheckforUpdate

**Expected behavior:** Say if there is an update or not
**Actual behavior:** Error dialog pops up

### Versions

Please include the OS and what version of the OS you're running.
Please include the version of Brackets. You can find it under `Help -> About Brackets` (Windows and Linux) or `Brackets -> About Brackets` (macOS)

**Comment by abose** [comment]
https://github.com/brackets-cont/brackets/issues/54
