### ISSUE TITLE
New Slack Channel

### ISSUE THREAD

**Issue by sprintr** [brackets-cont/brackets#5]
Please create a new slack channel to discuss further development of the new fork.

CC: @luke2m @yogo1212

**Comment by ScanuNicco** [comment]
Do we have to use Slack or could we use something open-source? Matrix maybe?

**Comment by luke2m** [comment]
I would rather setup a matrix channel as well.

**Comment by yogo1212** [comment]
i also think matrix is the best choice for being open source, accessible, and technologically sound.
slack, imho, can be ruled out immediately.
discord is fairly liberal but has some sour notes like having the possibility of banning accounts for using third-party clients.

https://matrix.to/#/%23brackets-cont:matrix.org

#brackets-cont:matrix.org

**Comment by yogo1212** [comment]
i went ahead and created a matrix room but i can't dedicate much time towards maintaining it.
if someone wants to help organise, that would be very appreciated.

individuals who want to handle messages within slack should look into the [slack puppet](https://matrix.org/docs/projects/bridge/matrix-puppet-slack).
afaik, bridging won't be possible with matrix.org and requires a self-hosted matrix server so a connection on the "organisation" level is infeasible atm.

**Comment by ScanuNicco** [comment]
> afaik, bridging won't be possible with matrix.org and requires a self-hosted matrix server so a connection on the "organisation" level is infeasible atm.

I actually host my own matrix server (matrix.scanuproductions.com) so we could use that if bridging becomes necessary

**Comment by sprintr** [comment]
Joined the matrix chat room but each message says `-- Encrypted Event (No keys found for decryption) --`. Can someone guide me to read decrypt and read the messages?

**Comment by ScanuNicco** [comment]
@sprintr I think that when encryption is enabled, you can't see messages from before you joined. Also double check that the matrix client you are using supports end-to-end encryption.

**Comment by sprintr** [comment]
@ScanuNicco I was only the 2nd person to join the room and most message are encrypted.

**Comment by sprintr** [comment]
![image](https://user-images.githubusercontent.com/3390089/126802238-ac985f1d-d097-404c-8970-c1a565a0c569.png)

@ScanuNicco This is what I see.

**Comment by ScanuNicco** [comment]
Hmm...

Are you logged in on multiple devices? If so, you might have to verify them with each other to ensure that the decryption keys transfer. You should click on your name in the room info and then you will see any unverified sessions under "Security".
![image](https://user-images.githubusercontent.com/30136040/126879247-48ea7af6-a8dc-46cb-863b-557cff1cb7d6.png)

If there are any unverified sessions, there should be an option to verify them.

**Comment by sprintr** [comment]
I am able to read the new message now. Closing this one for now.
