### ISSUE TITLE
Create Baseline test runs from last brackets release build

### ISSUE THREAD

**Issue by abose** [brackets-cont/brackets#52]
Baseline test suite at the last release:

https://github.com/brackets-cont/brackets/commit/d55ac606ac44e7169dbeaf959c9ed47dac6a6b9a

**Comment by mathewdennis1** [comment]
Brackets test report 12 Nov 2021 -->> [testing  - Brackets.pdf](https://github.com/brackets-cont/brackets/files/7522673/_brackets.testing.-.Brackets.pdf)

**Comment by abose** [comment]
Thanks, @mathewdennis1 For the baseline. 
Closing issue as done.
