### ISSUE TITLE
Notice on upstreams readme?

### ISSUE THREAD

**Issue by yashpalgoyal1304** [brackets-cont/brackets#56]
hi, shouldnt upstream [README.md](https://github.com/adobe/brackets/blob/master/README.md) file mention that the project's maintainence have been given to this brackets-cont ??

**Comment by abose** [comment]
The Upstream repo has been archived as read-only by Adobe preventing any changes. However, It has pinned this issue for notice: https://github.com/adobe/brackets/issues/15333 . 

Check out more details on brackets.io and the Twitter handle in the coming months as we move forward with the transition.
