### ISSUE TITLE
Fork wiki from Adobe repo

### ISSUE THREAD

**Issue by luke2m** [brackets-cont/brackets#7]
There is some great documentation in the adobe/brackets wiki and many links from the readme link to it. @yogo1212 or someone else with push access, would you do the following? It is not possible to do this with a PR. 
1. Make an empty Wiki page
2. `git clone https://github.com/adobe/brackets.wiki.git`
3. `git remote add fork https://github.com/brackets-cont/brackets.wiki.git`
4.  `git push -f fork master`

**Comment by yogo1212** [comment]
@luke2m done - thanks!
