### ISSUE TITLE
Create a custom download page for Brackets

### ISSUE THREAD

**Issue by charlypa** [brackets-cont/brackets#72]
Instead of showing a cluttered download page, offer a simple download page to display windows and mac installers.

**Comment by abose** [comment]
We can probably do something like this instead of a separate download page
![image](https://user-images.githubusercontent.com/5336369/142112888-94c57240-6962-41df-b16e-7af6e5c0720b.png)

**Comment by abose** [comment]
Closing as done.
We autodetect OS and initiate download based on the OS with a single download button.
