### ISSUE TITLE
[Installer] Brackets setup location error

### ISSUE THREAD

**Issue by onurbbr** [brackets-cont/brackets#83]
### Description

Brackets cannot be installed to the desired file location.

Brackets is installed to "C:\Program Files (x86)\Brackets" by default. I want to install it on the 2nd Disk because my disk space is low. The file I want to install is "E:\Programs\Brackets".

### Steps to Reproduce

1. Change installation folder
2. After the installation is finished I check the file location.

**Expected behavior:**
Installed to "E:\Programs\Brackets".

**Actual behavior:**
Installed to "C:\Program Files (x86)\Brackets".

### Versions
Windows 11 Pro Version 21H2 (OS Build 22000.348)
Brackets Version 2.0.0.prerelease

**Comment by abose** [comment]
Thanks for the error report 👍 will fix before the release

**Comment by abose** [comment]
@onurbbr This is fixed in the latest brackets pre-release builds. Please download here:  https://github.com/brackets-cont/brackets/releases
Closing as fixed. Please reopen if you face any issues.
Thanks!

**Comment by onurbbr** [comment]
Thanks for your feedback. Good work!
