### ISSUE TITLE
Sanity test pass in windows

### ISSUE THREAD

**Issue by abose** [brackets-cont/brackets#86]
Run against last pass: https://github.com/brackets-cont/brackets/issues/69
Run test on: 
https://github.com/brackets-cont/brackets/commit/4340a77515eeffd38b26cb959992e8390159268e
Previous test:
https://github.com/brackets-cont/brackets/commit/b3ed7977b8ba1a43c632ce10b9efb42be14e7f66

**Comment by mathewdennis1** [comment]
Test ran for 4340a77 against baseline  --

-  https://docs.google.com/spreadsheets/d/1h9HbbXAydSmbo3X5fiYkI9dBAyqit6vMRKXbkGkVk8A/edit#gid=0

- [_brackets testing.pdf](https://github.com/brackets-cont/brackets/files/7622857/_brackets.testing.-.Brackets.base.line.1.pdf)
